services:
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - ./config:/app/config
    ports:
      - 8080:8080
